sudo: required
services:
  - docker

before_install:
  - docker build -t timlavrysen/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true timlavrysen/docker-test npm run test -- --coverage