sudo: required
services:
  - docker

before_install:
  - docker build -t timlavrysen/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true timlavrysen/docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-442656431382"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"